# Generated by Django 5.1.3 on 2024-12-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_user_type_tutorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
