# Generated by Django 5.1.3 on 2024-12-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tutorprofile_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='profile_picture',
            field=models.ImageField(default='tutor_profiles/default.png', upload_to='tutor_profiles/'),
        ),
    ]
