# Generated by Django 6.0.1 on 2026-06-11 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tutorprofile_first_name_tutorprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('education_level', models.CharField(choices=[('middle_school', 'Middle School'), ('high_school', 'High School'), ('college', 'College'), ('graduate_school', 'Graduate School'), ('other', 'Other')], max_length=30)),
                ('rate_at_booking', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_sent', to=settings.AUTH_USER_MODEL)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to='core.tutorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
